# Generated by Django 4.1.7 on 2023-03-29 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RESOURCE_NAME', models.CharField(max_length=255, unique=True)),
                ('RESOURCE_URL', models.CharField(max_length=255, unique=True)),
                ('top_tag', models.JSONField()),
                ('bottom_tag', models.JSONField()),
                ('title_cut', models.JSONField()),
                ('date_cut', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('news_unix_date', models.BigIntegerField()),
                ('added_unix_date', models.BigIntegerField()),
                ('news_date', models.DateField()),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resources.resource')),
            ],
        ),
    ]
